#!/bin/bash
### BEGIN INIT INFO
# Provides:          grubtale
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Grubtale theme background generator
# Description:       Updates Grubtale GRUB theme background with system info
### END INIT INFO

# Variables
DAEMON="/usr/local/share/grubtale/grubtale.sh"
NAME="grubtale"
PIDFILE="/var/run/$NAME.pid"

# Source function library
. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $NAME"
        if start-stop-daemon --start --quiet --oknodo --exec $DAEMON -- generate; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    stop)
        log_daemon_msg "Stopping $NAME"
        log_end_msg 0
        ;;
    restart|force-reload)
        $0 stop
        $0 start
        ;;
    status)
        echo "$NAME background generator (manual execution)"
        ;;
    generate)
        log_daemon_msg "Generating $NAME background"
        if $DAEMON generate; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status|generate}"
        exit 1
        ;;
esac

exit 0
